# Generated by Django 4.0.1 on 2022-01-19 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_productfeatures'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productfeatures',
            old_name='feature',
            new_name='features',
        ),
    ]
