# Generated by Django 4.0.1 on 2022-01-17 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('pending', 'pending'), ('in progress', 'in progress'), ('Cancelled', 'Cancelled'), ('Delivered', 'Delivered')], default='pending', max_length=255),
        ),
    ]
